# Config for Integrated Gradients for SQuAD
model_checkpoint: "/content/drive/My Drive/MLR/v1_style/squad/model/squad-bert-base-uncased-model"
device: cuda
n_steps: 25
method: "riemann_right"
internal_batch_size: 4
n_samples: 1000
store_dir: "/content/drive/My Drive/MLR/v1_style/squad/IGv2/"
predictions_path: "/content/drive/My Drive/MLR/v1_style/squad/preds/squad_final_predictions.json"
