dataset_name: mlqa #The dataset to be loaded from datasets
subset_name: mlqa.hi.hi # The subset of data to load
model_checkpoint: bert-base-multilingual-uncased #Pretrained Tokenizer Name
max_length: 384 #Max Sequence Length
doc_stride: 128 #Document Stride
