#Args
model:
  pretrained_model_name: bert-base-uncased
args:
  output_dir: "/content/drive/My Drive/MLR/v1_style/duorc/ckpts/duorc-bert-base-uncased"
  logging_dir: "/content/drive/My Drive/MLR/v1_style/duorc/runs/"
  evaluation_strategy: epoch
  per_device_train_batch_size: 6
  per_device_eval_batch_size: 8
  weight_decay: 0.01
  learning_rate: 3e-5
  num_train_epochs: 2
  adam_epsilon: 1e-6
  lr_scheduler_type: polynomial
  warmup_steps: 2912 # 10% of total train setps - (116491*2)/8 * 0.1
  logging_first_step: true
  logging_steps: 1000
  save_steps: 2000
  seed: 2020
  dataloader_num_workers: 4
trainer:
  pretrained_tokenizer_name: bert-base-uncased
  save_model_name: "/content/drive/My Drive/MLR/v1_style/duorc/model/duorc-bert-base-uncased-model"
misc:
  squad_v2: false
  raw_predictions_file: "/content/drive/My Drive/MLR/v1_style/duorc/preds/duorc_raw"
  metric_file: "/content/drive/My Drive/MLR/v1_style/duorc/preds/duorc.json"
  final_predictions_file: "/content/drive/My Drive/MLR/v1_style/duorc/preds/duorc_final_predictions.json"
