#Args
model:
  pretrained_model_name: bert-base-multilingual-uncased
args:
  output_dir: "/content/drive/My Drive/MLR/xquad/ckpts/xquad-bert-base-multilingual-uncased"
  logging_dir: "/content/drive/My Drive/MLR/xquad/runs/"
  evaluation_strategy: epoch
  per_device_train_batch_size: 6
  per_device_eval_batch_size: 8
  weight_decay: 0.01
  learning_rate: 3e-5
  num_train_epochs: 2
  adam_epsilon: 1e-6
  lr_scheduler_type: polynomial
  warmup_steps: 2950 # 10% of total train setps - (88524*2)/6 * 0.1
  logging_first_step: true
  logging_steps: 1000
  save_steps: 2000
  seed: 2020
  dataloader_num_workers: 4
trainer:
  pretrained_tokenizer_name: bert-base-uncased
  save_model_name: "/content/drive/My Drive/MLR/xquad/model/xquad-bert-base-multilingual-uncased-model"
misc:
  squad_v2: false
  raw_predictions_file: "/content/drive/My Drive/MLR/xquad/preds/xquad_raw"
  metric_file: "/content/drive/My Drive/MLR/xquad/preds/xquad.json"
  final_predictions_file: "/content/drive/My Drive/MLR/xquad/preds/xquad_final_predictions.json"
